# Generated by Django 5.0.6 on 2024-05-28 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('job_title', models.TextField()),
                ('phone_number', models.TextField()),
                ('vk', models.URLField()),
                ('avatar_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.activity')),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
            bases=('core.activity',),
        ),
        migrations.CreateModel(
            name='Infrastucture',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.activity')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
            },
            bases=('core.activity',),
        ),
        migrations.CreateModel(
            name='CoordinatesEvent',
            fields=[
                ('coordinates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.coordinates')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='events.event')),
            ],
            bases=('core.coordinates',),
        ),
        migrations.CreateModel(
            name='CoordinatesInfrastucture',
            fields=[
                ('coordinates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.coordinates')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='events.infrastucture')),
            ],
            bases=('core.coordinates',),
        ),
        migrations.CreateModel(
            name='PhotoEvent',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.photo')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='events.event')),
            ],
            bases=('core.photo',),
        ),
        migrations.CreateModel(
            name='PhotoInfrastucture',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.photo')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='events.infrastucture')),
            ],
            bases=('core.photo',),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_id', models.IntegerField()),
                ('title', models.TextField()),
                ('chairman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region', to='events.chairman')),
            ],
        ),
        migrations.AddField(
            model_name='infrastucture',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastucture', to='events.region'),
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.region'),
        ),
        migrations.CreateModel(
            name='VideoEvent',
            fields=[
                ('video_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.video')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='events.event')),
            ],
            bases=('core.video',),
        ),
        migrations.CreateModel(
            name='VideoInfrastucture',
            fields=[
                ('video_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.video')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='events.infrastucture')),
            ],
            bases=('core.video',),
        ),
    ]
