# Generated by Django 5.0.6 on 2024-05-26 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.activity')),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            bases=('core.activity',),
        ),
        migrations.CreateModel(
            name='CoordinatesEvent',
            fields=[
                ('coordinates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.coordinates')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='events.event')),
            ],
            bases=('core.coordinates',),
        ),
        migrations.CreateModel(
            name='PhotoEvent',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.photo')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='events.event')),
            ],
            bases=('core.photo',),
        ),
        migrations.CreateModel(
            name='VideoEvent',
            fields=[
                ('video_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.video')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='events.event')),
            ],
            bases=('core.video',),
        ),
    ]
